package pl.put.poznan.plantsguard.model;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;

public class Measure {

	private LocalDateTime measureDateTime;
	@DynamoDBHashKey(attributeName="MeasureDate")
	private String measureDate;
	@DynamoDBIndexRangeKey(attributeName="MeasureTime")
	private String measureTime;
	@DynamoDBAttribute(attributeName="humidity")
	private Float humidity;
	@DynamoDBAttribute(attributeName="temperature")
	private Float temperature;
	@DynamoDBAttribute(attributeName="soil")
	private Float soil;
	@DynamoDBAttribute(attributeName="light")
	private Float light;
	
	public Measure() {
		this.measureDateTime = LocalDateTime.now();
		this.measureDate = LocalDateTime.now().format(DateTimeFormatter.ISO_DATE).toString();
		this.measureTime = measureDateTime.format(DateTimeFormatter.ISO_TIME).toString();
	}

	public Measure(Float humidity, Float temperature, Float soil, Float light) {
		super();
		this.measureDateTime = LocalDateTime.now();
		this.measureDate = this.measureDateTime.format(DateTimeFormatter.ISO_DATE).toString();
		this.measureTime = this.measureDateTime.format(DateTimeFormatter.ISO_TIME).toString();
		this.humidity = humidity;
		this.temperature = temperature;
		this.soil = soil;
		this.light = light;
	}

	public String getMeasureDate() {
		return this.measureDate;
	}

	public String getMeasureTime() {
		return this.measureTime;
	}
	
	public LocalDateTime getMeasureLocalDateTime() {
		return this.measureDateTime;
	}
	
	public void setMeasureDate(LocalDateTime measureDateTime) {
		this.measureDateTime = measureDateTime;
		this.measureDate = this.measureDateTime.format(DateTimeFormatter.ISO_DATE).toString();
		this.measureTime = this.measureDateTime.format(DateTimeFormatter.ISO_TIME).toString();
	}

	public Float getHumidity() {
		return humidity;
	}

	public void setHumidity(Float humidity) {
		this.humidity = humidity;
	}

	public Float getTemperature() {
		return temperature;
	}

	public void setTemperature(Float temperature) {
		this.temperature = temperature;
	}

	public Float getSoil() {
		return soil;
	}

	public void setSoil(Float soil) {
		this.soil = soil;
	}

	public Float getLight() {
		return light;
	}

	public void setLight(Float light) {
		this.light = light;
	}
}
