version: 0.2;
option_settings:
  aws:elasticbeanstalk:xray:
    XRayEnabled: true
phases:
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - '**/*'
  base-directory: 'target/Plantsguard'